package runtime

import (
	"fmt"
	"hash/crc32"
	"sort"
	"strings"
)

type contextPromotionCandidate struct {
	sourceKind string
	sourceID   string
	summary    string
	priority   string
	order      int
	parallel   *ParallelCandidate
	thread     *OpenThread
}

func (s *Service) PromoteContextJobs(limit int, dispatch bool) (AgentJobPromotionResult, error) {
	packet := s.Knowledge()
	candidates := buildContextPromotionCandidates(packet)
	sort.SliceStable(candidates, func(i, j int) bool {
		left := contextPriorityRank(candidates[i].priority)
		right := contextPriorityRank(candidates[j].priority)
		if left == right {
			leftKind := contextSourceRank(candidates[i].sourceKind)
			rightKind := contextSourceRank(candidates[j].sourceKind)
			if leftKind == rightKind {
				return candidates[i].order < candidates[j].order
			}
			return leftKind < rightKind
		}
		return left > right
	})

	result := AgentJobPromotionResult{
		GeneratedAt: zeroSafeNow(),
		Items:       []AgentJobPromotionItem{},
	}
	existingJobs := indexAgentJobsByID(s.ListAgentJobs())
	actioned := 0
	for _, candidate := range candidates {
		job, reason, ok := candidate.agentJob()
		if !ok {
			result.Considered++
			result.Items = append(result.Items, AgentJobPromotionItem{
				SourceKind: candidate.sourceKind,
				SourceID:   candidate.sourceID,
				Summary:    candidate.summary,
				Status:     "skipped",
				Reason:     reason,
			})
			continue
		}
		if limit > 0 && actioned >= limit {
			break
		}
		result.Considered++
		actioned++

		item, err := s.ensurePromotedContextJob(candidate, job, dispatch, existingJobs, &result)
		if err != nil {
			return result, err
		}
		result.Items = append(result.Items, item)
	}
	return result, nil
}

func buildContextPromotionCandidates(packet KnowledgePacket) []contextPromotionCandidate {
	items := make([]contextPromotionCandidate, 0, len(packet.ParallelCandidates)+len(packet.OpenThreads))
	proposalThreads := proposalCandidateThreadSet(packet.ProposalCandidates)
	order := 0
	for _, candidate := range packet.ParallelCandidates {
		copy := candidate
		items = append(items, contextPromotionCandidate{
			sourceKind: "parallel_candidate",
			sourceID:   parallelCandidateSourceID(copy),
			summary:    strings.TrimSpace(copy.Text),
			priority:   normalizeContextPriority(copy.Priority),
			order:      order,
			parallel:   &copy,
		})
		order++
	}
	for _, thread := range packet.OpenThreads {
		copy := thread
		if _, covered := proposalThreads[strings.TrimSpace(copy.ThreadID)]; covered {
			continue
		}
		items = append(items, contextPromotionCandidate{
			sourceKind: "open_thread",
			sourceID:   strings.TrimSpace(copy.ThreadID),
			summary:    strings.TrimSpace(copy.Question),
			priority:   normalizeContextPriority(openThreadPriority(copy)),
			order:      order,
			thread:     &copy,
		})
		order++
	}
	return items
}

func proposalCandidateThreadSet(items []ProposalCandidate) map[string]struct{} {
	covered := map[string]struct{}{}
	for _, item := range items {
		for _, threadID := range item.ThreadIDs {
			threadID = strings.TrimSpace(threadID)
			if threadID == "" {
				continue
			}
			covered[threadID] = struct{}{}
		}
	}
	return covered
}

func (c contextPromotionCandidate) agentJob() (AgentJob, string, bool) {
	switch {
	case c.parallel != nil:
		return agentJobFromParallelCandidate(*c.parallel)
	case c.thread != nil:
		return agentJobFromOpenThread(*c.thread)
	default:
		return AgentJob{}, "no context source available", false
	}
}

func agentJobFromOpenThread(item OpenThread) (AgentJob, string, bool) {
	summary := strings.TrimSpace(limitText(item.Question, 140))
	if summary == "" {
		return AgentJob{}, "open thread question is empty", false
	}
	switch openThreadKind(item) {
	case openThreadKindStale:
		return AgentJob{}, "memory-hygiene thread requires explicit founder state update", false
	}
	priority := normalizeContextPriority(openThreadPriority(item))
	now := zeroSafeNow()
	payload := map[string]any{
		"autogenerated": true,
		"source_kind":   "open_thread",
		"thread_id":     strings.TrimSpace(item.ThreadID),
		"thread_kind":   openThreadKind(item),
		"priority":      priority,
		"pattern_refs":  append([]string{}, item.PatternRefs...),
		"evidence":      append([]string{}, item.Evidence...),
	}
	return AgentJob{
		JobID:     deriveContextJobID("open_thread", strings.TrimSpace(item.ThreadID)),
		Kind:      "plan",
		Role:      "planner",
		Summary:   summary,
		Status:    "queued",
		Source:    "knowledge.open_thread",
		Surface:   SurfaceAPI,
		Stage:     StageDiscover,
		Payload:   payload,
		Notes:     []string{"auto_promoted", "context:open_thread", "priority:" + priority},
		CreatedAt: now,
		UpdatedAt: now,
	}, "", true
}

func agentJobFromParallelCandidate(item ParallelCandidate) (AgentJob, string, bool) {
	summary := strings.TrimSpace(limitText(item.Text, 140))
	if summary == "" {
		return AgentJob{}, "parallel candidate text is empty", false
	}
	kind := strings.TrimSpace(item.Kind)
	source := strings.TrimSpace(item.Source)
	reason := strings.TrimSpace(item.Reason)
	priority := normalizeContextPriority(item.Priority)
	if kind == "agent_job" {
		return AgentJob{}, "parallel candidate already points to an agent job", false
	}
	if kind == "approval" {
		return AgentJob{}, "approval step requires explicit founder decision", false
	}
	if kind == "release" || kind == "rollback" {
		return AgentJob{}, kind + " step requires explicit founder transition", false
	}
	if source == "founder_view.now" {
		return AgentJob{}, "active work stays explicit until external execution is less lock-bound", false
	}

	jobKind := ""
	role := ""
	stage := Stage("")
	switch {
	case strings.Contains(strings.ToLower(reason), "review-room"):
		jobKind = "plan"
		role = "planner"
		stage = StageDiscover
	case kind == "proposal":
		jobKind = "plan"
		role = "planner"
		stage = StageDiscover
	case kind == "flow" && source == "founder_view.risk":
		jobKind = "verify"
		role = "verifier"
		stage = StageVerify
	default:
		return AgentJob{}, "candidate is not agent-safe for auto-promotion yet", false
	}

	now := zeroSafeNow()
	payload := map[string]any{
		"autogenerated":    true,
		"source_kind":      "parallel_candidate",
		"candidate_kind":   kind,
		"candidate_source": source,
		"candidate_reason": reason,
		"priority":         priority,
		"text":             summary,
	}
	if ref := normalizeRef(item.Ref); ref != nil {
		payload["candidate_ref"] = *ref
	}
	return AgentJob{
		JobID:     deriveContextJobID("parallel_candidate", parallelCandidateSourceID(item), kind, summary, source, reason),
		Kind:      jobKind,
		Role:      role,
		Summary:   summary,
		Status:    "queued",
		Source:    "knowledge.parallel_candidate",
		Surface:   SurfaceAPI,
		Stage:     stage,
		Ref:       normalizeRef(item.Ref),
		Payload:   payload,
		Notes:     []string{"auto_promoted", "context:parallel_candidate", "priority:" + priority},
		CreatedAt: now,
		UpdatedAt: now,
	}, "", true
}

func (s *Service) ensurePromotedContextJob(candidate contextPromotionCandidate, job AgentJob, dispatch bool, existingJobs map[string]AgentJob, result *AgentJobPromotionResult) (AgentJobPromotionItem, error) {
	if existing, ok := existingJobs[job.JobID]; ok {
		result.Existing++
		item := AgentJobPromotionItem{
			SourceKind: candidate.sourceKind,
			SourceID:   candidate.sourceID,
			Summary:    candidate.summary,
			Status:     "existing",
			Job:        copyAgentJobPtr(existing),
		}
		if dispatch && (existing.Status == "queued" || existing.Status == "failed") {
			return s.dispatchPromotedContextJob(item, existing.JobID, existingJobs, result), nil
		}
		return item, nil
	}
	if err := s.CreateAgentJob(job); err != nil {
		if strings.Contains(strings.ToLower(err.Error()), "job_id already exists") {
			if existing, ok := findAgentJobByID(s.ListAgentJobs(), job.JobID); ok {
				existingJobs[job.JobID] = existing
				result.Existing++
				item := AgentJobPromotionItem{
					SourceKind: candidate.sourceKind,
					SourceID:   candidate.sourceID,
					Summary:    candidate.summary,
					Status:     "existing",
					Job:        copyAgentJobPtr(existing),
				}
				if dispatch && (existing.Status == "queued" || existing.Status == "failed") {
					return s.dispatchPromotedContextJob(item, existing.JobID, existingJobs, result), nil
				}
				return item, nil
			}
		}
		return AgentJobPromotionItem{}, err
	}
	existingJobs[job.JobID] = job
	result.Created++
	item := AgentJobPromotionItem{
		SourceKind: candidate.sourceKind,
		SourceID:   candidate.sourceID,
		Summary:    candidate.summary,
		Status:     "created",
		Job:        copyAgentJobPtr(job),
	}
	if dispatch {
		return s.dispatchPromotedContextJob(item, job.JobID, existingJobs, result), nil
	}
	return item, nil
}

func (s *Service) dispatchPromotedContextJob(item AgentJobPromotionItem, jobID string, existingJobs map[string]AgentJob, result *AgentJobPromotionResult) AgentJobPromotionItem {
	dispatchResult, err := s.DispatchAgentJob(jobID)
	if err != nil {
		item.Status = "dispatch_failed"
		item.Reason = err.Error()
		result.Failed++
		if current, ok := findAgentJobByID(s.ListAgentJobs(), jobID); ok {
			existingJobs[jobID] = current
			item.Job = copyAgentJobPtr(current)
		}
		return item
	}
	result.Dispatched++
	existingJobs[jobID] = dispatchResult.Job
	item.Status = "dispatched"
	item.Job = copyAgentJobPtr(dispatchResult.Job)
	item.Dispatch = copyDispatchResultPtr(dispatchResult)
	return item
}

func copyAgentJobPtr(item AgentJob) *AgentJob {
	copy := item
	return &copy
}

func copyDispatchResultPtr(item AgentDispatchResult) *AgentDispatchResult {
	copy := item
	return &copy
}

func indexAgentJobsByID(items []AgentJob) map[string]AgentJob {
	indexed := make(map[string]AgentJob, len(items))
	for _, item := range items {
		indexed[item.JobID] = item
	}
	return indexed
}

func findAgentJobByID(items []AgentJob, jobID string) (AgentJob, bool) {
	trimmed := strings.TrimSpace(jobID)
	for _, item := range items {
		if strings.TrimSpace(item.JobID) == trimmed {
			return item, true
		}
	}
	return AgentJob{}, false
}

func parallelCandidateSourceID(item ParallelCandidate) string {
	if ref := normalizeRef(item.Ref); ref != nil {
		return *ref
	}
	return fmt.Sprintf("candidate_%08x", crc32.ChecksumIEEE([]byte(strings.Join([]string{
		strings.TrimSpace(item.Kind),
		strings.TrimSpace(item.Source),
		strings.TrimSpace(item.Reason),
		strings.TrimSpace(item.Text),
	}, "|"))))
}

func deriveContextJobID(parts ...string) string {
	normalized := make([]string, 0, len(parts))
	for _, part := range parts {
		normalized = append(normalized, strings.TrimSpace(part))
	}
	return fmt.Sprintf("job_ctx_%08x", crc32.ChecksumIEEE([]byte(strings.Join(normalized, "|"))))
}

func normalizeContextPriority(priority string) string {
	switch strings.TrimSpace(strings.ToLower(priority)) {
	case "high":
		return "high"
	case "low":
		return "low"
	default:
		return "medium"
	}
}

func contextPriorityRank(priority string) int {
	switch normalizeContextPriority(priority) {
	case "high":
		return 3
	case "medium":
		return 2
	default:
		return 1
	}
}

func contextSourceRank(kind string) int {
	switch strings.TrimSpace(kind) {
	case "parallel_candidate":
		return 0
	case "open_thread":
		return 1
	default:
		return 2
	}
}
