package runtime

type SurfaceSpec struct {
	CLIUsage    []string
	CLIDispatch []string
	APIRoutes   []string
}

var canonicalCLIUsage = []string{
	"layer-osctl status [--allow-local-fallback]",
	"layer-osctl daemon status",
	"layer-osctl daemon wait [--timeout 10s] [--interval 250ms]",
	"layer-osctl handoff [--allow-local-fallback]",
	"layer-osctl knowledge",
	"layer-osctl next",
	"layer-osctl conversation status",
	"layer-osctl conversation note --text <text> [--source <source-channel>] [--summary <text>] [--tags a,b] [--refs a,b] [--confidence low|medium|high] [--actor <actor>] [--captured-at <rfc3339>] [--auto-plan true|false] [--auto-risk true|false] [--auto-dispatch true|false] [--llm-tag true|false]",
	"layer-osctl telegram preview",
	"layer-osctl threads status",
	"layer-osctl threads publish --approval <approval-id>",
	"layer-osctl session bootstrap [--full] [--allow-local-fallback]",
	"layer-osctl session checkpoint --focus <text> [--goal <text>] [--steps a,b] [--risks a,b] [--handoff <text>] [--note <text>] [--refs a,b]",
	"layer-osctl session note --text <text> [--kind note|todo|decision|risk] [--refs a,b]",
	"layer-osctl session finish --focus <text> [--goal <text>] [--steps a,b] [--risks a,b] [--handoff <text>] [--note <text>]",
	"layer-osctl review-room [--allow-local-fallback] | [add|accept|defer|resolve] ...",
	"layer-osctl writer",
	"layer-osctl adapters",
	"layer-osctl provider list",
	"layer-osctl ingest antigravity [--root <path>] [--run <id>] [--limit <n>] [--job <job-id>] [--status <succeeded|failed|canceled>] [--dry-run]",
	"layer-osctl ingest telegram [--topic <topic>] [--interaction inbound_conversation|outbound_publication|feedback_reply|youtube_link_injection|bookmark_share] [--title <text>] [--summary <text>] [--excerpt <text>|--excerpt-file <path>] [--url <url>] [--direction inbound|outbound|feedback] [--kind message|link|publication|feedback] [--message-id <id>] [--chat <id>] [--username <name>] [--actor <actor>] [--confidence low|medium|high] [--tags a,b] [--refs a,b] [--captured-at <rfc3339>] [--dry-run]",
	"layer-osctl ingest content [--channel crawler|personal_db|notebook_lm] [--profile note|summary|qa|transcript|bookmark|outline|article|video|thread|post|content_capture] [--topic <topic>] [--title <text>] [--summary <text>] [--excerpt <text>|--excerpt-file <path>] [--url <url>] [--author <text>] [--kind article|note|bookmark|video|content_capture] [--doc-id <id>] [--actor <actor>] [--confidence low|medium|high] [--tags a,b] [--refs a,b] [--captured-at <rfc3339>] [--dry-run]",
	"layer-osctl ingest rss --feed <url> [--limit <n>] [--channel <source-channel>] [--kind <article|video|thread|post|content_capture>] [--topic <topic>] [--actor <actor>] [--author <text>] [--tags a,b] [--refs a,b] [--dry-run]",
	"layer-osctl ingest gemini [--root <path>] [--limit <n>] [--job <job-id>] [--status <succeeded|failed|canceled>] [--cleanup] [--dry-run]",
	"layer-osctl ingest corpus [--limit <n>] [--cleanup] [--dry-run]",
	"layer-osctl corpus list",
	"layer-osctl corpus search --query <text>",
	"layer-osctl observation list [--channel <source-channel>] [--topic <topic>] [--actor <actor>] [--ref <ref>] [--text <text>] [--limit <n>]",
	"layer-osctl observation create [--id <id>] --channel <source-channel> --topic <topic> --summary <text> [--excerpt <text>] [--actor <actor>] [--confidence low|medium|high] [--refs a,b] [--captured-at <rfc3339>]",
	"layer-osctl thread list [--limit <n>]",
	"layer-osctl capabilities",
	"layer-osctl event list",
	"layer-osctl event create --kind <kind> [--surface api|cockpit|telegram] [--work <id>] [--stage discover|compose|experience|verify|release] [--data a=b,c=d]",
	"layer-osctl event stream",
	"layer-osctl auth status",
	"layer-osctl auth set [--token <token>]",
	"layer-osctl auth clear",
	"layer-osctl preflight list",
	"layer-osctl preflight create --id <id> --task <text> [--mode internal] [--status ready|degraded-lite|needs_clarification] [--decision go|hold]",
	"layer-osctl verify list",
	"layer-osctl verify run --id <id> [--scope kernel] [--notes a,b]",
	"layer-osctl gateway list",
	"layer-osctl gateway create --id <id> [--decision <id>] [--provider <text>] [--model <text>] [--kind <text>] [--status <text>] [--budget <n>] [--notes a,b]",
	"layer-osctl branch list",
	"layer-osctl branch create --id <id> --title <text> --intent <text> [--summary <text>] [--stage discover|compose|experience|verify|release] [--surface api|cockpit|telegram] [--parent <branch-id>] [--basis-ref <ref>] [--notes a,b]",
	"layer-osctl branch merge --id <branch-id> --target <branch-id> [--notes a,b]",
	"layer-osctl proposal list",
	"layer-osctl proposal create --id <id> --title <text> --intent <text> [--summary <text>] [--surface api|cockpit|telegram] [--branch <branch-id>] [--priority <text>] [--risk <text>] [--notes a,b]",
	"layer-osctl proposal promote --id <proposal-id> --work <work-id>",
	"layer-osctl job list [--status queued|running|succeeded|failed|canceled|open] [--limit <n>]",
	"layer-osctl job profiles",
	"layer-osctl job packet --id <job-id>",
	"layer-osctl job create --id <id> --kind <kind> --role <role> --summary <text> --source <source> [--surface api|cockpit|telegram] [--branch <branch-id>] [--stage discover|compose|experience|verify|release] [--ref <ref>] [--notes a,b] [--allowed-paths a,b] [--payload-json <json>] [--council claude,openai] [--council-primary claude]",
	"layer-osctl job update --id <job-id> --status <queued|running|succeeded|failed|canceled> [--notes a,b] [--result a=b,c=d] [--result-file <path>] [--result-json <json>]",
	"layer-osctl job report --id <job-id> --status <succeeded|failed|canceled> [--notes a,b] [--result a=b,c=d] [--result-file <path>] [--result-json <json>]",
	"layer-osctl job dispatch --id <job-id>",
	"layer-osctl job work --command <shell-command> [--roles planner,implementer,verifier,designer] [--dispatch-queued] [--once] [--poll 30s] [--limit 1] [--work-root <path>] [--repo-root <path>] [--stop-on-failure] [--idle-exit-after 10m] [--packet-file <path>]",
	"layer-osctl quickwork [--summary <text>] [--role implementer|verifier|planner|designer] [--allowed-paths a,b] [--payload-json <json>] [--council claude,openai] [--council-primary claude] [--loop] [--poll 10s] [--exit-on-idle 10m] [--up|--status|--down]",
	"layer-osctl work list",
	"layer-osctl work create --id <id> --title <text> --intent <text> [--stage discover] [--surface api] [--branch <branch-id>]",
	"layer-osctl founder summary [--allow-local-fallback]",
	"layer-osctl founder start --flow <id> --work <id> --approval <id> --title <text> --intent <text> [--notes a,b]",
	"layer-osctl founder approve --flow <id> [--notes a,b]",
	"layer-osctl founder release --flow <id> --release <id> --deploy <id> [--target vm] [--channel cockpit] [--notes a,b]",
	"layer-osctl founder rollback --flow <id> --rollback <id> [--notes a,b]",
	"layer-osctl snapshot export [--file path]",
	"layer-osctl snapshot import --file path",
	"layer-osctl flow list",
	"layer-osctl flow create --id <id> --work <id> [--status active|waiting|released|rolled_back|blocked] [--notes a,b]",
	"layer-osctl flow sync --id <id> --work <id> [--approval <id>] [--policy <id>] [--execute <id>] [--verify <id>] [--release <id>] [--deploy <id>] [--rollback <id>] [--notes a,b]",
	"layer-osctl approval list",
	"layer-osctl approval create --id <id> --work <id> --summary <text> [--stage verify] [--surface cockpit]",
	"layer-osctl approval resolve --id <id> --status <approved|rejected>",
	"layer-osctl policy evaluate --id <id> --work <id> [--approval <id>] [--risk low|medium|high] [--novelty low|medium|high] [--reversible] [--deployable] [--dispatchable]",
	"layer-osctl execute run --id <id> --policy <id> [--decision go|hold] [--notes a,b]",
	"layer-osctl release list",
	"layer-osctl release create --id <id> --work <id> --target <target> --channel <channel> [--artifacts a,b] [--approvals a,b]",
	"layer-osctl deploy list",
	"layer-osctl deploy create --id <id> --release <id> [--target <target>] [--status succeeded|failed] [--notes a,b]",
	"layer-osctl deploy execute --id <id> --release <id> [--notes a,b]",
	"layer-osctl rollback list",
	"layer-osctl rollback create --id <id> --release <id> [--deploy <id>] [--target <target>] [--status recorded|succeeded|failed] [--notes a,b]",
	"layer-osctl rollback execute --id <id> --release <id> [--deploy <id>] [--notes a,b]",
	"layer-osctl memory get",
	"layer-osctl memory set --focus <text> [--goal <text>] [--steps a,b] [--risks a,b] [--handoff <text>] [--operator <name>]",
	"layer-osctl target list",
	"layer-osctl target put --id <id> --command /absolute/path/to/bin,arg1,arg2 [--workdir <absolute-path>]",
	"layer-osctl audit structure [--strict]",
	"layer-osctl audit contracts [--strict]",
	"layer-osctl audit residue [--strict]",
	"layer-osctl audit gemini [--strict]",
	"layer-osctl audit corpus [--strict]",
	"layer-osctl audit authority [--strict]",
	"layer-osctl audit surface [--strict]",
	"layer-osctl audit security [--strict]",
	"layer-osctl audit review-room [--strict]",
	"layer-osctl audit runtime-data [--strict]",
	"layer-osctl audit mcp [--strict]",
	"layer-osctl audit docs [--strict]",
	"layer-osctl smoke cockpit",
}

var canonicalCLIDispatch = []string{
	`"status":`,
	`"daemon":`,
	`"handoff":`,
	`"session":`,
	`"review-room":`,
	`"knowledge":`,
	`"next":`,
	`"telegram":`,
	`"threads":`,
	`"writer":`,
	`"adapters":`,
	`"provider":`,
	`"ingest":`,
	`"corpus":`,
	`"conversation":`,
	`"observation":`,
	`"thread":`,
	`"capabilities":`,
	`"founder":`,
	`"preflight":`,
	`"gateway":`,
	`"event":`,
	`"release":`,
	`"deploy":`,
	`"rollback":`,
	`"target":`,
	`"branch":`,
	`"proposal":`,
	`"job":`,
	`"quickwork":`,
	`"work":`,
	`"flow":`,
	`"approval":`,
	`"auth":`,
	`"memory":`,
	`"snapshot":`,
	`"policy":`,
	`"execute":`,
	`"audit":`,
	`"verify":`,
	`"smoke":`,
}

var canonicalAPIRoutes = []string{
	`/api/layer-os/daemon`,
	`/api/layer-os/status`,
	`/api/layer-os/handoff`,
	`/api/layer-os/review-room`,
	`/api/layer-os/adapters`,
	`/api/layer-os/writer`,
	`/api/layer-os/session/bootstrap`,
	`/api/layer-os/session/checkpoint`,
	`/api/layer-os/session/note`,
	`/api/layer-os/session/finish`,
	`/api/layer-os/events`,
	`/api/layer-os/events/stream`,
	`/api/layer-os/knowledge`,
	`/api/layer-os/telegram`,
	`/api/layer-os/social/threads`,
	`/api/layer-os/providers`,
	`/api/layer-os/founder-view`,
	`/api/layer-os/corpus/entries`,
	`/api/layer-os/corpus/recover`,
	`/api/layer-os/knowledge/search`,
	`/api/layer-os/conversation`,
	`/api/layer-os/observations`,
	`/api/layer-os/source-intake`,
	`/api/layer-os/source-intake/drafts/prep`,
	`/api/layer-os/open-threads`,
	`/api/layer-os/threads`,
	`/api/layer-os/capabilities`,
	`/api/layer-os/founder-summary`,
	`/api/layer-os/founder-actions/start`,
	`/api/layer-os/founder-actions/approve`,
	`/api/layer-os/founder-actions/release`,
	`/api/layer-os/founder-actions/rollback`,
	`/api/layer-os/cockpit`,
	`/api/layer-os/releases`,
	`/api/layer-os/deploys`,
	`/api/layer-os/deploys/execute`,
	`/api/layer-os/rollbacks`,
	`/api/layer-os/rollbacks/execute`,
	`/api/layer-os/deploy-targets`,
	`/api/layer-os/branches`,
	`/api/layer-os/branches/merge`,
	`/api/layer-os/proposals`,
	`/api/layer-os/proposals/promote`,
	`/api/layer-os/jobs/profiles`,
	`/api/layer-os/jobs/packet`,
	`/api/layer-os/jobs`,
	`/api/layer-os/jobs/promote`,
	`/api/layer-os/jobs/update`,
	`/api/layer-os/jobs/report`,
	`/api/layer-os/jobs/dispatch`,
	`/api/layer-os/work-items`,
	`/api/layer-os/flows`,
	`/api/layer-os/flows/sync`,
	`/api/layer-os/approval-inbox`,
	`/api/layer-os/approval-inbox/resolve`,
	`/api/layer-os/auth`,
	`/api/layer-os/preflights`,
	`/api/layer-os/memory`,
	`/api/layer-os/snapshot`,
	`/api/layer-os/policies`,
	`/api/layer-os/policies/evaluate`,
	`/api/layer-os/gateway-calls`,
	`/api/layer-os/execute-runs`,
	`/api/layer-os/execute-runs/run`,
	`/api/layer-os/verifications`,
	`/api/layer-os/verifications/run`,
	`/api/layer-os/audit/structure`,
	`/api/layer-os/audit/contracts`,
	`/api/layer-os/audit/residue`,
	`/api/layer-os/audit/gemini`,
	`/api/layer-os/audit/authority`,
	`/api/layer-os/audit/surface`,
	`/api/layer-os/audit/security`,
	`/api/layer-os/audit/review-room`,
	`/api/layer-os/audit/runtime-data`,
	`/api/layer-os/audit/mcp`,
	`/api/layer-os/audit/docs`,
}

func CanonicalSurfaceSpec() SurfaceSpec {
	return SurfaceSpec{
		CLIUsage:    append([]string{}, canonicalCLIUsage...),
		CLIDispatch: append([]string{}, canonicalCLIDispatch...),
		APIRoutes:   append([]string{}, canonicalAPIRoutes...),
	}
}
