version: '3'

services:
  # Snapshot Daemon - 시스템 스냅샷 생성 및 관리
  snapshot-daemon:
    image: python:3.11-slim
    container_name: 97layer-snapshot

    volumes:
      # 메인: 전체 프로젝트 (호스트와 공유 - 소스, 설정, knowledge만)
      - /Users/97layer/97layerOS:/app:Z
      # 오버레이: 임시 파일/로그는 컨테이너 내부 전용 (호스트 격리)
      - 97layer-tmp:/app/.tmp
      - 97layer-drive-cache:/app/.tmp.driveupload
      - snapshot-logs:/app/logs

    working_dir: /app
    command: python3 execution/snapshot_daemon.py

    # 환경변수 (.env 파일에서 자동 로드)
    env_file:
      - /Users/97layer/97layerOS/.env

    environment:
      - ENVIRONMENT=MACBOOK
      - PROCESSING_MODE=parallel
      - ENABLE_MULTIMODAL=true
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1

    # 자동 재시작
    restart: unless-stopped

    # 헬스체크 (선택)
    healthcheck:
      test: ["CMD", "python3", "-c", "import os; exit(0 if os.path.exists('/app/task_status.json') else 1)"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 30s

    # 로깅 설정
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  # GCP Management Server - GCP 리소스 관리
  gcp-management:
    image: python:3.11-slim
    container_name: 97layer-gcp-mgmt

    volumes:
      # 메인: 전체 프로젝트 (호스트와 공유)
      - /Users/97layer/97layerOS:/app:Z
      # 오버레이: 임시 파일/로그는 컨테이너 내부 전용
      - 97layer-tmp:/app/.tmp
      - 97layer-drive-cache:/app/.tmp.driveupload
      - gcp-logs:/app/logs

    working_dir: /app
    command: python3 execution/ops/gcp_management_server.py

    env_file:
      - /Users/97layer/97layerOS/.env

    environment:
      - ENVIRONMENT=MACBOOK
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1

    # 포트 매핑 (컨테이너 8888 → 호스트 8081)
    ports:
      - "8081:8888"

    restart: unless-stopped

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  # Realtime Receiver - 실시간 데이터 수신
  realtime-receiver:
    image: python:3.11-slim
    container_name: 97layer-receiver

    volumes:
      # 메인: 전체 프로젝트 (호스트와 공유)
      - /Users/97layer/97layerOS:/app:Z
      # 오버레이: 임시 파일/로그는 컨테이너 내부 전용
      - 97layer-tmp:/app/.tmp
      - 97layer-drive-cache:/app/.tmp.driveupload
      - receiver-logs:/app/logs

    working_dir: /app
    command: python3 execution/ops/mac_realtime_receiver.py

    env_file:
      - /Users/97layer/97layerOS/.env

    environment:
      - ENVIRONMENT=MACBOOK
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1

    # 포트 매핑 (컨테이너 9876 → 호스트 9876)
    ports:
      - "9876:9876"

    restart: unless-stopped

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

# 볼륨 정의
volumes:
  # 공유 임시 볼륨 (모든 컨테이너가 같은 .tmp, drive cache 공유)
  97layer-tmp:
    driver: local
  97layer-drive-cache:
    driver: local

  # 컨테이너별 로그 볼륨
  snapshot-logs:
    driver: local
  gcp-logs:
    driver: local
  receiver-logs:
    driver: local

# 네트워크 (선택 - 필요 시 컨테이너 간 통신)
networks:
  default:
    name: 97layer-network
    driver: bridge
