version: '3'

services:
  nightguard:
    # 경량 Python 이미지
    build:
      context: ..
      dockerfile: deployment/Dockerfile.nightguard

    container_name: 97layer-nightguard
    hostname: nightguard-vm

    # 볼륨 마운트 (virtiofs 최적화 - Linux에서는 자동)
    volumes:
      - /home/ubuntu/97layerOS:/app:Z
      - nightguard-tmp:/app/.tmp

    working_dir: /app

    # Night Guard 데몬 실행
    command: python3 execution/system/nightguard_daemon.py

    # 자원 할당 및 Swap 메모리 (핵심 최적화)
    mem_limit: 700m           # RAM 700MB 제한
    mem_reservation: 500m     # 최소 500MB 보장
    memswap_limit: 2700m      # RAM 700MB + Swap 2GB = 2700MB
    cpus: '1'                 # CPU 1코어

    # 헬스체크 자동화 (5분마다)
    healthcheck:
      test: ["CMD", "python3", "execution/system/health_check.py"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 30s

    # 자동 재시작 (헬스체크 실패 시)
    restart: unless-stopped

    # Podman Secrets 연동 (API 키 보안)
    secrets:
      - telegram_bot_token
      - gemini_api_key
      - anthropic_api_key

    # 환경변수
    environment:
      - ENVIRONMENT=GCP_VM
      - PROCESSING_MODE=sequential
      - ENABLE_MULTIMODAL=false
      - MEMORY_LIMIT_MB=700
      - AI_MODEL_PREFERENCE=gemini-1.5-flash

      # Secrets를 환경변수로 매핑
      - TELEGRAM_BOT_TOKEN_FILE=/run/secrets/telegram_bot_token
      - GEMINI_API_KEY_FILE=/run/secrets/gemini_api_key
      - ANTHROPIC_API_KEY_FILE=/run/secrets/anthropic_api_key

    # 로깅 설정 (디스크 공간 절약)
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

    # 네트워크 (격리)
    networks:
      - nightguard-net

# Podman Secrets 정의
secrets:
  telegram_bot_token:
    external: true
  gemini_api_key:
    external: true
  anthropic_api_key:
    external: true

# 볼륨 정의
volumes:
  nightguard-tmp:
    driver: local

# 네트워크 정의
networks:
  nightguard-net:
    driver: bridge
