#!/usr/bin/env bash
# report_now.sh — 한 줄로 요약 리포트 생성 + evidence 기록
# 사용:
#   core/scripts/report_now.sh --summary "오늘 작업" --next "배포 확인" --agent codex
# 옵션:
#   --summary (-s)    완료 요약 (필수, 멀티라인 가능: 따옴표로 감싸기)
#   --next (-n)       다음 단계 (여러 번 지정 가능)
#   --improve (-i)    개선/보완 사항 (여러 번 지정 가능)
#   --agent (-a)      에이전트 ID (기본 codex)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
REPORT_SCRIPT="${ROOT}/core/system/compact_report.py"
EVIDENCE_GUARD="${ROOT}/core/system/evidence_guard.py"
REPORT_DIR="${ROOT}/knowledge/reports/daily"

if [[ ! -f "$REPORT_SCRIPT" ]]; then
  echo "compact_report.py not found" >&2
  exit 1
fi

SUMMARY=""
AGENT="codex"
NEXT_ARGS=()
IMPROVE_ARGS=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --summary|-s) SUMMARY="${2:-}"; shift 2 ;;
    --next|-n)    NEXT_ARGS+=("--next-step" "${2:-}"); shift 2 ;;
    --improve|-i) IMPROVE_ARGS+=("--improvement" "${2:-}"); shift 2 ;;
    --agent|-a)   AGENT="${2:-}"; shift 2 ;;
    *) echo "Unknown arg: $1" >&2; exit 1 ;;
  esac
done

if [[ -z "${SUMMARY}" ]]; then
  echo "요약(--summary) 은 필수입니다." >&2
  exit 2
fi

mkdir -p "$REPORT_DIR"

# generate report
python3 "$REPORT_SCRIPT" --agent-id "$AGENT" --summary "$SUMMARY" "${NEXT_ARGS[@]}" "${IMPROVE_ARGS[@]}" --improvement-from-next

# pick latest compact report
LATEST="$(python3 - <<'PY'\nimport pathlib\nfrom datetime import datetime, timedelta\nroot = pathlib.Path(__file__).resolve().parents[2]\ndirp = root / 'knowledge' / 'reports' / 'daily'\nfiles = sorted(dirp.glob('compact_*.md'), key=lambda p: p.stat().st_mtime, reverse=True)\nprint(files[0] if files else '')\nPY)"

if [[ -n "$LATEST" && -f "$LATEST" ]]; then
  DETAIL="compact report generated by report_now.sh"
  python3 "$EVIDENCE_GUARD" --append --claim "Compact report generated (manual trigger)" --evidence-type file --source "$LATEST" --detail "$DETAIL"
  echo "✅ Evidence recorded for $LATEST"
else
  echo "⚠️  compact report not found; evidence not recorded"
fi
